In [1]:
import numpy as np

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a_1 = a.reshape(2, 6)
a_2 = a.reshape(3, 4)
a_3 = a.reshape(4, 3)
a_4 = a.reshape(6, 2)
a_5 = a.reshape(12, 1)

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a_1 = a.reshape(2, -1)
a_2 = a.reshape(-1, 4)
a_3 = a.reshape(4, -1)
a_4 = a.reshape(-1, 2)
a_5 = a.reshape(12, -1)

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
print(f"{a.reshape(12, 1).ndim}-мерный массив")

2-мерный массив


Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
a = np.random.randn(3, 4)
print(a)

[[-1.38175825  0.05262722 -0.35357261 -0.19329675]
 [ 0.04362273 -1.09498626  1.03249507  1.5748565 ]
 [-1.19404435 -0.42188068  0.89792438 -0.18404051]]


In [7]:
b = a.flatten()
print(b)

[-1.38175825  0.05262722 -0.35357261 -0.19329675  0.04362273 -1.09498626
  1.03249507  1.5748565  -1.19404435 -0.42188068  0.89792438 -0.18404051]


In [8]:
a.size == b.size

True

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [9]:
a = np.arange(20, 0, -2)

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [10]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(f"Размерность массива a - {a.ndim}")
print(f"Размерность массива b - {b.ndim}")

Размерность массива a - 1
Размерность массива b - 2


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [11]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму
этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу
At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную
матрицу для матрицы B и почему?

In [13]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.transpose()
B = A.dot(At)
print(B.shape)
print(np.linalg.det(B))

(4, 4)
0.0


In [14]:
# вычислить обратную матрицу для матрицы B не представляется возможным, т.к. её определитель равен 0.
# Это означает, что ранг матрицы B меньше числа её строк.
print(np.linalg.matrix_rank(B) < B.shape[0])

True


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [15]:
a = np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [16]:
c = np.linspace(0, 15, 16)

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [17]:
C = c.reshape(4, 4)
D = B + C * 10
D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)

In [18]:
print(f'Определитель матрицы D: {D_det}')
print(f'Ранк матрицы D: {D_rank}')
print(f'Обратная матрица D_inv:\n {D_inv}')

Определитель матрицы D: 5.18953807259442e-26
Ранк матрицы D: 2
Обратная матрица D_inv:
 [[ 4.66062690e+13 -1.49229688e+13 -1.09972869e+14  7.82895692e+13]
 [ 1.63480451e+14 -3.81454387e+14  2.72467419e+14 -5.44934838e+13]
 [-4.66779710e+14  8.07677680e+14 -2.15016230e+14 -1.25881740e+14]
 [ 2.56692989e+14 -4.11300324e+14  5.25216801e+13  1.02085655e+14]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [19]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1

In [20]:
print(D_inv)

[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 1.]]


In [21]:
E = np.where(D_inv == 1, B, C)

In [22]:
print(E)

[[  5.   1.   2.  32.]
 [ 14.   5.  86.   7.]
 [  8.  86.  10.  11.]
 [ 32.  13. 212. 302.]]
